### ISSUE TITLE
Placeholder Not coloring right

### ISSUE THREAD

**Issue by Lokifisch** [PlaceholderAPI/PlaceholderAPI#1115]
### Confirmation

- [x] My issue isn't already found on the Issue tracker.
- [x] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [x] The issue isn't already fixed in a Spigot Release or Development Build.
- [x] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

Plugin Bug

### What happens?

in my Paper server(1.21.4) i have placeholderapi, teaks tweaks and shyscoreboard installed i colored the placeholder like this 
```yaml
title: "&aLokismp.com"
# Displayed lines of the scoreboard. Supports placeholders. Max length of a line is 32 characters.
lines:
  - "&6★ Welcome:&r %player_list_name%"
  - "&2✈ Ping: %player_ping%"
  - "&4❤ Health: %math_0:round_{player_health}%"
  - "&5🏆 Rank:&r %luckperms_prefix%"
  - "§9⌚ Time: §9%localtime_time_H:m:s%"
  - "&2&l$&r&2 Money:&r %vault_eco_balance_commas%$"
  - "&3☺ Playtime:&r %playtime_time%"
```

i use teaks tweaks to turn the &3 into §3 it works bun sometimes the whole placeholder doesnt get colored

![Image](https://github.com/user-attachments/assets/dbb4137d-2793-449f-8551-13119a2befee)

as you see not the whole time gets colored

### Expected Behaviour

it should color the whole placeholder

### How to Reproduce

use Paper 1.21.4 with placeholder api and teaks tweaks and shyscoreboard
then activate the colored thext feture in teakstweaks 
then in shyscoreboard make the scoreboard like this 
```yaml
# Unique identifier of a scoreboard.
name: "Test"
# Possible types: GLOBAL, COMMAND, WORLDGUARD
# If GLOBAl, the scoreboard is always visible as long as the player has got the permission shyscoreboard.scoreboard.sample_scoreboard.
# If COMMAND, the scoreboard is only visible after executing the command /shyscoreboard add sample_scoreboard AND having the permission shyscoreboard.scoreboard.sample_scoreboard.
# If WORLDGUARD, the scoreboard is only visible after entering a WorldGuard region where the flag shyscoreboard has been set to this scoreboard name.
type: "GLOBAL"
# If multiple scoreboards would be available, the one with the highest priority (lowest number), is selected.
priority: 0
# The Minecraft ticks how often this scoreboard is updated to the player. (1 tick = 50ms)
refreshTicks: 5
# Displayed title of the scoreboard. Supports placeholders. Max length of the title is 16 characters.
title: "&aLokismp.com"
# Displayed lines of the scoreboard. Supports placeholders. Max length of a line is 32 characters.
lines:
  - "&6★ Welcome:&r %player_list_name%"
  - "&2✈ Ping: %player_ping%"
  - "&4❤ Health: %math_0:round_{player_health}%"
  - "&5🏆 Rank:&r %luckperms_prefix%"
  - "§9⌚ Time: §9%localtime_time_H:m:s%"
  - "&2&l$&r&2 Money:&r %vault_eco_balance_commas%$"
  - "&3☺ Playtime:&r %playtime_time%"
```

### `/papi dump` Output

https://paste.helpch.at/esitivajil

### Additional Info

if i should use §3 then please let me know
