### ISSUE TITLE
MarriageMaster Placeholder issues

### ISSUE THREAD

**Issue by MithrandirCraft** [PlaceholderAPI/PlaceholderAPI#156]
Relevant external tickets:
https://github.com/GeorgH93/MarriageMaster/issues/72
https://github.com/kangarko/ChatControl-Pro/issues/1319

MarriageMaster: 2.0.8
ChatControlPro: 8.3.4
PAPI: 2.10.3
Spigot: 1.13.2

MarriageMaster recently updated and changed it's placeholders. I reported issues with the new placeholders used on ChatControl's HOVER_EVENT inside the plugin's formatting.yml, to MM's developer, however both him and ChatControl's developer's suggested this may be some one else's issue, lastly I was sent here.

The exact issue is that MarriageMaster's placeholders won't work on ChatControl.

### Expected behaviour
It should forward the placeholders from MarriageMaster to ChatControl properly

### Actual behaviour
Variables/placeholders aren't substituted in ChatControl's formatting.yml

### How to reproduce
(Untested, may test myself, however it shouldn't be necessary since this is very close to my main server setup)
0. Clean spigot server
1. Download and install ChatControlPro (Or maybe just the free ChatControl, allthough I do not guarantee it'll have the features)
2. Download and install MarriageMaster
3. Download and install PAPI
4. Inside plugins/chatcontrolpro/formatting.yml, edit the chat format so that someone shown on a chat line uses a HOVER_EVENT which shows text on hover over the text, use marriage master's placeholders.

MM's placeholders: https://github.com/GeorgH93/MarriageMaster/wiki/Placeholders
How it looks ingame: 
![imagen](https://user-images.githubusercontent.com/6623704/62155288-bb993100-b308-11e9-8466-5488748f7b1a.png)
Specific format.yml config example:
```   
Player:
      Message: '{nick} '
      Hover_Event:
        Action: SHOW_TEXT
        Values:
        - '&8*-----* &f{player} &8*-----*'
        - '&7Rango/s&8: &f{pl_group}'
        - '&7Mundo: &f{world}'
        - '&7Pareja: {marriagemaster_heart} {marriagemaster_partner}'
```
