### ISSUE TITLE
ParseOther Not showing called placeholder in deluxe menu lore

### ISSUE THREAD

**Issue by NoExtraSauce** [PlaceholderAPI/PlaceholderAPI#249]
[Request change (Wiki)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_wiki.md
[Request change (PlaceholderAPI)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_placeholderapi.md
[Spigot]: https://www.spigotmc.org/resources/6245/
[Jenkins]: http://ci.extendedclip.com/job/PlaceholderAPI/
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues

## Please read
This template is only for reporting bugs of PlaceholderAPI!  
If you want to request changes to the code of PlaceholderAPI, use the [Request change (PlaceholderAPI)] template.  
For changes to the wiki use the [Request change (Wiki)] template.

Please also make sure that you use the [latest release][Spigot] or the latest [developement build][Jenkins] and that your bug isn't already reported on the [issues] page.

**Please report issues with expansions/placeholders to the corresponding issue tracker! Only report it here if you can't find any place to report it!**

### Issue
> What is the issue? Describe it like you would tell a friend.

ParseOther Expansion doesn't show placeholders of other expansions when using {target} arg in deluxe menus. It will show the placeholder for my own player username but not other player usernames. I am testing it with offline players usernames that have joined my server in the past. Placeholder expansions I tested this with are 'Statz' & 'Statistic'

Furthering this, the called placeholder will disappear if 'update: true' is enabled in deluxe menus

### Expected behaviour
> What should PlaceholderAPI do?

`- '%parseother_{{target}}_{statz_deaths}%'` should show the death stat based on the {target} username entered in the command to open the menu. Works on my own player just not others.

### Actual behaviour
> What does PlaceholderAPI actually do?

Doesn't show the placeholder instead the lore is just blank.

### How to reproduce
> What steps did you made, to get this bug?

Run the menu inside deluxe menus with either of these two expansions: 'Statz' & 'Statistic'
Then run the command in game with another players name. '/othersstats (username)'

Menu YML:
```
menu_title: "&e{target}'s Stats"
open_command: 'othersstats'
size: 27
args:
  target: 1
args_usage_message: "&6/othersstats {target}"
open_requirement:
  requirements:
    permission:
      type: has permission
      permission: menu.realmmenu
      deny_commands:
      - '[message] &cYou dont have permission...'
items:
  player_stats:
    material: head;{target}
    update: false
    hide_enchantments: true
    enchantments:
      - MENDING;1
    slot: 3
    display_name: "&9{target}'s Stats"
    lore:
    - '%parseother_{{target}}_{statz_deaths}%'
```
