### ISSUE TITLE
Cant detect what potion player has, only material name

### ISSUE THREAD

**Issue by broken1arrow** [PlaceholderAPI/PlaceholderAPI#511]
## Feature Request

make it possible to actually read which potion player has (in clear command you need to type the potion).

Did not manage to get anything that can actually read if a vanilla command succeeds or not.

The name on a potion .

name: potion Material: POTION
Potion (string): Minecraft:long_fire_resistance

Spigot name long_fire_resistance

### 

It is for not only sell potion , it is for buy this potions too.

- [ ] New function for PlaceholderAPI.  
A new function that developers could use.
- [ ] Change to code (Internal).  
Changes to code that won't affect the end-user.
- [ ] Change to code (External).  
Changes to code that will affect the end-user (breaks stuff).
- [ ] Other: __________ 

### Description

It is for not only sell potion , it is for buy this potions too. So it give great different on the server if it has this.

**Comment by broken1arrow** [comment]
If it was reable way to detect you could buy it from players and even change lore if you have item or not.
Like this example, if you don´t have the item you don´t get sell part in the lore. 

And the check item I use only work if you add a lore to the item and is not a good way to fix the problem.

<details>
 <summary>example menu</summary>
```
  '1_no_potion':
    material: potion
    slot: 10
    priority: 8
    view_requirement:
      potion:
         type: string equals
         input: '%checkitem_lorecontains:Häxbrygd Night Vision (3:00)%'
         output: 'no'
         material: 'POTION'
      money_requirement:
        type: '>='
        input: '%vault_eco_balance_fixed%'
        output: 300
    display_name: '&2Häxbrygd Night Vision'
    lore:
    - ''
    - '&6&l<&#ff0537&lYou dont have'
    - '&#ff0537&lpotion of Night Vision&6&l>'
    - ''
    - '------------------'
    - '&aYou have:  %vault_eco_balance_fixed% &eⒼ'
    - '&b• buy: 300 gold'
  #  - '&b• Sell: 30 gold'
    - '------------------'
    - '&8 (left click for buy)'
   # - '&8 (right click for sell)'

``` 
</details>
