### ISSUE TITLE
minecraft user name question

### ISSUE THREAD

**Issue by qian403** [PlaceholderAPI/PlaceholderAPI#995]
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

Plugin Bug

### What happens?
I have tried paper and purper but both have the same result
my friends player ign is **player_unfounded** When he exits the game, the command line will pop up an error message,after investigation, only the player will log out and an error will occur,I'm not sure what's going wrong, am I under-installing dependencies or am I missing something
![image](https://github.com/PlaceholderAPI/PlaceholderAPI/assets/89014784/b22e8076-af44-411b-b4cf-3e1ff7e93354)
![image](https://github.com/PlaceholderAPI/PlaceholderAPI/assets/89014784/c53f3778-4e22-4354-8b85-5e89a1270a80)

### Expected Behaviour

Error messages should not pop up continuously

### How to Reproduce

1.player name is player_unfounded 
2.join a game
3.left a game

### `/papi dump` Output

https://paste.helpch.at/awiqaqotul

### Console Log

https://paste.helpch.at/itimufiroc.makefile

### Errors

https://paste.helpch.at/rotibicaha.md

### Additional Info
Please let me know if I missed anything

**Comment by iGabyTM** [comment]
How does your config for "tabplugin" looks like?

**Comment by Andre601** [comment]
The errors first of all point to an expansion provided by some plugin, so this is most likely an issue by whatever this plugin is that adds this expansion.

**Comment by qian403** [comment]
> How does your config for "tabplugin" looks like?

> 您的「標籤外掛程式」配置是什麼樣的？
i use this https://www.spigotmc.org/resources/tab-plugin-1-20.110126/
and this is my config file
```yml
#The config for changing your tablist!
#NOTE: ALWAYS use "" for text. PlaceholderAPI + Animations are supported! Find more information at https://github.com/Niall7459/KiteBoard-Documentation/wiki/Animations-and-Modifiers
#If you still see %...% do '/papi ecloud download player' + '/papi ecloud download server' + '/papi ecloud download animations'
#Change the header here.
Header: "%animations_<shine>------------------------------</shine>%"
#Change the footer here.
Footer: "%animations_<shine>------------------------------</shine>%\n §aTPS: %server_tps_1_colored% - Uptime: %server_uptime% - Player online: %server_online% "
#Change the amount of ticks when updating the tablist. 20 ticks equals 1 second. 
#If your number is high, the tablist will be updated slowly. When your number is low, the tablist will be updated frequently. I recommend using 5 as number.
UpdateDelay: 5
```
